version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    container_name: "front"
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/front/node_modules
    restart: always